### ISSUE TITLE
Push can fail quietly in GitHub Action

### ISSUE THREAD

**Issue by edhgoose** [githubocto/repo-visualizer#9] opened 2021-08-05 23:10 UTC
This could be the same as #2 - but quieter?

We're seeing something unusual where it looks like the commit and push is working fine, and yet nothing appears in our git repo when using the GitHub Action.

Our output from the action looks as follows:

```
/usr/bin/git add ./diagram.svg
/usr/bin/git status --porcelain ./diagram.svg
A  diagram.svg

A  diagram.svg
diff: A  diagram.svg

/usr/bin/git commit -m Repo visualizer: updated diagram
/usr/bin/git push
[development 274d2128] Repo visualizer: updated diagram
 1 file changed, 1 insertion(+)
 create mode 100644 diagram.svg
Everything up-to-date
All set!
```

Yet commit `274d2128` does not exist on the development branch anywhere to be seen!

I'm wondering where it has gone?

We don't see any other error messages, and I cannot determine any setting that looks to forbid pushing to the branch. We're not getting an error like #2, although we do have the protected branches on. So I'm wondering if we _should_ be seeing the same issue?

We resorted to `cat`'ing the file out and copying it out - we're just playing anyway, so it's not critical :) 

P.s. Thanks for this tool - it's really interesting to see our code visualised in this way.

**Comment by etienne-martin** [comment] 2021-08-05 23:15
Do you think this could be caused by the missing `await` here?

https://github.com/githubocto/repo-visualizer/blob/main/src/index.jsx#L45

**Comment by etienne-martin** [comment] 2021-08-05 23:25
Ok seems like it did the trick, I forked the repo, added the missing await and now it works.

Can you try with [my fork](https://github.com/etienne-martin/repo-visualizer) to see if it fixed the issue for you?

```diff
name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
-        uses: githubocto/repo-visualizer@main
+        uses: etienne-martin/repo-visualizer@main
        with:
          excluded_paths: ".github"
```

I'll follow up with a PR shortly.

**Comment by Wattenberger** [comment] 2021-08-06 14:54
good catch, PR merged! Let me know if you're still seeing this @edhgoose

**Closed by Wattenberger** 2021-08-06 14:54 UTC
